using VMMC.Models;

namespace VMMC.IServices
{
    public interface IMaster
    {
        #region Access Level
        Task<bool> CreateUpdateAccessLevel(AccessLevel _accessLevel);
        Task<string> AutoGeneratedAccessid();
        Task<List<AccessLevel>> GetAccrssLevel();
        Task<AccessLevel> AccessLevelEdit(int id);
        Task<bool> AccessLevelDelete(int id);
        #endregion
        #region Roles 
        Task<bool> CreateUpdateRoles(Role _role);
        Task<List<Role>> RolesDetails();
        Task<Role> RolesEdit(int id);
        Task<bool> Rolesdelete(int id);
        Task<string> AutoGeneratedRoleId();
        #endregion

    }
}
